version: 2
jobs:
  build:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0-browsers
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            - v1-dependencies-
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential
      - run: make unit
      - save_cache:
          key: v1-dependencies-{{ checksum "deps.edn" }}
          paths:
            - ~/.m2
